/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cudaTuner.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4294c84dc9fa0ba785fded05da3538ca)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cudaCourse/cudaTuner.h>
// pydoc.h is automatically generated in the build directory
#include <cudaTuner_pydoc.h>

void bind_cudaTuner(py::module& m)
{

    using cudaTuner    = ::gr::cudaCourse::cudaTuner;


    py::class_<cudaTuner, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<cudaTuner>>(m, "cudaTuner", D(cudaTuner))

        .def(py::init(&cudaTuner::make),
           py::arg("blockSize"),
           py::arg("chunkSize"),
           py::arg("sampleRate"),
           py::arg("freq"),
           py::arg("phase"),
           D(cudaTuner,make)
        )
        



        ;




}








