/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cudaDecimatingFirFilter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(faf559fccdad9df7985f862ccbd8551a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cudaCourse/cudaDecimatingFirFilter.h>
// pydoc.h is automatically generated in the build directory
#include <cudaDecimatingFirFilter_pydoc.h>

void bind_cudaDecimatingFirFilter(py::module& m)
{

    using cudaDecimatingFirFilter    = ::gr::cudaCourse::cudaDecimatingFirFilter;


    py::class_<cudaDecimatingFirFilter, gr::block, gr::basic_block,
        std::shared_ptr<cudaDecimatingFirFilter>>(m, "cudaDecimatingFirFilter", D(cudaDecimatingFirFilter))

        .def(py::init(&cudaDecimatingFirFilter::make),
           py::arg("blockSize"),
           py::arg("chunkSize"),
           py::arg("decimationFactor"),
           py::arg("taps"),
           D(cudaDecimatingFirFilter,make)
        )
        



        ;




}








